# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-03 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('physician', models.CharField(max_length=250)),
                ('serviceProvider', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refer.Referral'),
        ),
    ]
