# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
